### ISSUE TITLE
1. Getting Started

### ISSUE THREAD

**Issue by lizstangle** [MakeSchool-Tutorials/ecommerce-tutorial#1]
Please explain the bug you found here.
I had to create a new dev2 folder. [oh-my-zsh] Insecure completion-dependent directories detected:
drwxrwxr-x  3 liz  admin   96 Aug 17 14:55 /usr/local/share/zsh
drwxrwxr-x  6 liz  admin  192 Aug 19 21:30 /usr/local/share/zsh/site-functions

[oh-my-zsh] For safety, we will not load completions from these directories until
[oh-my-zsh] you fix their permissions and ownership and restart zsh.
[oh-my-zsh] See the above list for directories with group or other writability.

[oh-my-zsh] To fix your permissions you can do so by disabling
[oh-my-zsh] the write permission of "group" and "others" and making sure that the
[oh-my-zsh] owner of these directories is either root or your current user.
[oh-my-zsh] The following command may help:
[oh-my-zsh]     compaudit | xargs chmod g-w,o-w

[oh-my-zsh] If the above didn't help or you want to skip the verification of
[oh-my-zsh] insecure directories you can set the variable ZSH_DISABLE_COMPFIX to
[oh-my-zsh] "true" before oh-my-zsh is sourced in your zshrc file.

➜  ~ ls
Applications      Documents         Movies            Pictures          ResidentEvil2.txt greetings.txt     shots
Bar               Downloads         Music             Public            dev               move-me-gently    support#
Desktop           Library           Personal          README.md         folder-list.txt   outlast.txt
➜  ~ sudo chmod -r +rwx dev
Password:
chmod: +rwx: No such file or directory
➜  ~ cd dev
➜  dev ls -ltr
ls: .: Permission denied
➜  dev ls
ls: .: Permission denied
➜  dev

**Comment by ibirnam** [comment]
hey @lizstangle - this does not appear to be an issue with the tutorial, but rather with oh-my-zsh. I would recommend getting help from your instructor or in CoWork!
