### ISSUE TITLE
1. Getting Started

### ISSUE THREAD

**Issue by sicaramacuya** [MakeSchool-Tutorials/ecommerce-tutorial#3]
I didn't find any bug I'm just to give feedback. I don't know if is there a reason why in the step called "Set Up Git/GitHub" there is no explanation for what the point ( . ),  -m and -u does. At least I would have appreciated a simple explanation of what each command does. 

I don't know if down the line this will be explain but if not it will be great if you guys can consider the changes.

**Comment by ibirnam** [comment]
hey @sicaramacuya - don't worry, this will be explained in our classes! We didn't want to overwhelm too much in this initial tutorial, you will learn the rest later on!
